---
title: "UKBB-MH-Demographics.1"
author: "Simon Schwab"
date: "21 June 2018"
output: html_notebook
---

## Libraries
```{r message=FALSE}
library(ggplot2)
library(cowplot)
library(testit)
```

## Variables
```{r}
PATH_HOME = '/home/simon'
PATH_PROJ = file.path(PATH_HOME, 'Data', 'UKBB-MH') # Project path
PATH_RESULTS = file.path(PATH_PROJ, 'results')
PATH_FIGS = file.path(PATH_PROJ, 'figures')
PATH_UKBB = file.path(PATH_HOME, 'Drive', 'ukbiobank')
```

## Load subject info
```{r}
load(file = file.path(PATH_UKBB, 'UKBB-MH.RData'))
mydata = MYUKBB.2.matched
N=nrow(mydata)
Ng=N/3

assert(sum(mydata$hasfMRI) == N)

is.ctrl = mydata$is.control
is.pati = mydata$is.MD
is.risk = mydata$is.risk

# create group variable
group = rep(NA, N)
group[is.ctrl] = "control"
group[is.pati] = "patient"
group[is.risk] = "risk"
group = as.factor(group)
mydata$group = group
```

## Variable names
```{r}
names(mydata)
```

## Group sizes
```{r}
summary(mydata$group)
```

## Gender
```{r}
round(summary(mydata$sex[is.ctrl])/Ng, digits = 2)
round(summary(mydata$sex[is.pati])/Ng, digits = 2)
round(summary(mydata$sex[is.risk])/Ng, digits = 2)

prop.test(c(summary(mydata$sex[is.ctrl])[1],
            summary(mydata$sex[is.pati])[1],
            summary(mydata$sex[is.risk])[1]),
          rep(Ng, 3))
```

## Age
```{r}
table=array(NA, dim=c(3,2))

table[1,1] = mean(mydata$age[is.ctrl]); table[1,2] = sd(mydata$age[is.ctrl]);
table[2,1] = mean(mydata$age[is.pati]); table[2,2] = sd(mydata$age[is.pati]);
table[3,1] = mean(mydata$age[is.risk]); table[3,2] = sd(mydata$age[is.risk]);
rownames(table) = c("controls", "patients", "at-risk")
colnames(table) = c("mean", "sd")
print(table)

summary(aov(age ~ group, data = mydata))
```

## Ethnic background
```{r}
round(summary(mydata$ethnic.background[is.ctrl])/Ng, digits = 2)
round(summary(mydata$ethnic.background[is.pati])/Ng, digits = 2)
round(summary(mydata$ethnic.background[is.risk])/Ng, digits = 2)

prop.test(c(summary(mydata$ethnic.background[is.ctrl])[8],
            summary(mydata$ethnic.background[is.pati])[8],
            summary(mydata$ethnic.background[is.risk])[8]),
          rep(Ng, 3))
```

## Education
```{r}
s = "College or University degree"
sum(mydata$education[is.ctrl] == s, na.rm = T) / Ng
sum(mydata$education[is.pati] == s, na.rm = T) / Ng
sum(mydata$education[is.risk] == s, na.rm = T) / Ng

prop.test(c(sum(mydata$education[is.ctrl] == s, na.rm = T),
            sum(mydata$education[is.pati] == s, na.rm = T),
            sum(mydata$education[is.risk] == s, na.rm = T)),
          rep(Ng, 3)
)
```







